import {
  STOCK_CARD_ACTION_CONTEXT,
  STOCK_CARD_ADD_TO_SHIPMENT,
  STOCK_CARD_ALL_LOCATIONS,
  STOCK_CARD_ASSOCIATIONS,
  STOCK_CARD_BIN_LOCATIONS,
  STOCK_CARD_CURRENT_STOCK,
  STOCK_CARD_DEMAND,
  STOCK_CARD_DETAILS,
  STOCK_CARD_DOCUMENTS,
  STOCK_CARD_INVENTORY_LEVEL,
  STOCK_CARD_LOT_NUMBERS,
  STOCK_CARD_PENDING_INBOUND,
  STOCK_CARD_PENDING_OUTBOUND,
  STOCK_CARD_RECORD_INVENTORY,
  STOCK_CARD_SNAPSHOT,
  STOCK_CARD_STOCK_HISTORY,
  STOCK_CARD_SUPPLIERS,
  STOCK_CARD_TRANSACTION_LOG,
  STOCK_CARD_TRANSFER_STOCK,
  STOCK_CARD_UPDATE_INVENTORY_ITEM,
} from 'api/urls';
import apiClient from 'utils/apiClient';

export default {
  getDetails: (id, config) => apiClient.get(STOCK_CARD_DETAILS(id), config),
  getCurrentStock: (id, config) => apiClient.get(STOCK_CARD_CURRENT_STOCK(id), config),
  getStockHistory: (id, config) => apiClient.get(STOCK_CARD_STOCK_HISTORY(id), config),
  getAllLocations: (id, config) => apiClient.get(STOCK_CARD_ALL_LOCATIONS(id), config),
  getSuppliers: (id, config) => apiClient.get(STOCK_CARD_SUPPLIERS(id), config),
  getAssociations: (id, config) => apiClient.get(STOCK_CARD_ASSOCIATIONS(id), config),
  getPendingInbound: (id, config) => apiClient.get(STOCK_CARD_PENDING_INBOUND(id), config),
  getPendingOutbound: (id, config) => apiClient.get(STOCK_CARD_PENDING_OUTBOUND(id), config),
  getDemand: (id, config) => apiClient.get(STOCK_CARD_DEMAND(id), config),
  getSnapshot: (id, config) => apiClient.get(STOCK_CARD_SNAPSHOT(id), config),
  getDocuments: (id, config) => apiClient.get(STOCK_CARD_DOCUMENTS(id), config),
  getLotNumbers: (id, config) => apiClient.get(STOCK_CARD_LOT_NUMBERS(id), config),
  getTransactionLog: (id, config) => apiClient.get(STOCK_CARD_TRANSACTION_LOG(id), config),
  getActionContext: (config) => apiClient.get(STOCK_CARD_ACTION_CONTEXT, config),
  getBinLocations: (config) => apiClient.get(STOCK_CARD_BIN_LOCATIONS, config),
  getRecordInventory: (config) => apiClient.get(STOCK_CARD_RECORD_INVENTORY, config),
  getInventoryLevel: (config) => apiClient.get(STOCK_CARD_INVENTORY_LEVEL, config),
  updateInventoryLevel: (data, config) => apiClient.post(STOCK_CARD_INVENTORY_LEVEL, data, config),
  transferStock: (data, config) => apiClient.post(STOCK_CARD_TRANSFER_STOCK, data, config),
  updateInventoryItem: (data, config) =>
    apiClient.post(STOCK_CARD_UPDATE_INVENTORY_ITEM, data, config),
  addToShipment: (data, config) => apiClient.post(STOCK_CARD_ADD_TO_SHIPMENT, data, config),
};
